// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgmzusrwhdauegamhata.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnbXp1c3J3aGRhdWVnYW1oYXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwMjk3MjEsImV4cCI6MjA1MDYwNTcyMX0.-Usp46d6kDSegISaQqOkNEQsnVc_Y-F3Gno1OJvX4G0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);